version: '3.9'

services:
  bookaband-page:
    build:
      context: ./bookaband-page
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: unless-stopped
    networks:
      - default

  bookaband-auth:
    build:
      context: ./bookaband-auth
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    restart: unless-stopped
    networks:
      - default

  bookaband-app:
    build:
      context: ./bookaband-app
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    name: bookaband-network
    external: true
